### ISSUE TITLE
Make usernames case insensitive.

### ISSUE THREAD

**Issue by PCGeekBrain** [PCGeekBrain/chaverim-update#2]
Cast usernames to lowercase when they are submitted to the `usersController`

**Comment by PCGeekBrain** [comment]
@M2168J I see you are not using valid E-mails in the system. Do you want me to change it to case-insensitive usernames?

**Comment by M2168J** [comment]
Gut voch.

Yes, that would be fine.

**Comment by PCGeekBrain** [comment]
Ok, will be in the next update
