### ISSUE TITLE
Password issues

### ISSUE THREAD

**Issue by M2168J** [PCGeekBrain/chaverim-update#4]
Issue creating new account, password criteria seems confusing

**Comment by PCGeekBrain** [comment]
I don't think I set any hard criteria, just that it's "Dropbox rating" be 2/4 minimum. 

Should I change this?

For more details see the Dropbox repository it uses: https://github.com/dropbox/zxcvbn

**Comment by M2168J** [comment]
Can you set it to be a minimum of 6 characters, 1 capital, 1 number, no
spaces?

**Comment by PCGeekBrain** [comment]
I can definitely add it to the list of features to be changed when I can find the time to code :+1: .

**Comment by PCGeekBrain** [comment]
I have merged the code and it should be going live now
